config/routes.rb
Devise::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get "headings/index"
  get "aboutus_help/help"
  get "aboutus_help/aboutus"
  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  resources :dashboard
  resources :sections
  resources :headings
  resources :homepage
  resources :aboutus_help

  root to: "homepage#index"

end

app/models/heading.rb
class Heading < ActiveRecord::Base
  belongs_to :section

  searchable do
    text :H_Name, :H_Address, :H_Phone
  end
end

app/models/section.rb
class Section < ActiveRecord::Base
  has_many :headings

  searchable do
    text :Sec_Name
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/aboutus_help_controller.rb
class AboutusHelpController < ApplicationController
  def index

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
redirect_to homepage_path
  end
end

app/controllers/headings_controller.rb
class HeadingsController < ApplicationController
  before_action :set_heading, only: [:show, :edit, :update, :destroy]
  def index
    @section = Section.all
    @heading = Heading.all
       @search = Heading.search do
        fulltext params[:search]
      end
     @headings = @search.results
  end
  # GET /headings/1
  # GET /headings/1.json
  def show
    @heading = Heading.find(params[:id])
    @section = Section.find(params[:id])
  end

  # GET /headings/new
  def new
    @heading = Heading.new
    @headings = Heading.all
    @sectionn = Section.all
  end

  # GET /headings/1/edit
  def edit
  end

  # POST /headings
  # POST /headings.json
  def create

    @heading = Heading.new(heading_params)

    respond_to do |format|
      if @heading.save
        format.html { redirect_to @heading, notice: 'Heading was successfully created.' }
        format.json { render action: 'show', status: :created, location: @heading }
      else
        format.html { render action: 'new' }
        format.json { render json: @heading.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /headings/1
  # PATCH/PUT /headings/1.json
  def update
    respond_to do |format|
      if @heading.update(heading_params)
        format.html { redirect_to @heading, notice: 'Heading was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @heading.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /headings/1
  # DELETE /headings/1.json
  def destroy
    @heading.destroy
    respond_to do |format|
      format.html { redirect_to headings_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_heading
    @heading = Heading.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def heading_params
    params.require(:heading).permit(:H_Name, :H_Phone, :H_Address, :section_id)
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
    @last_three = Heading.last(3)
    @sections = Section.all
    @headings = Heading.all

      if user_signed_in?
    render 'homepage/index'
      end
  end
  end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def index
    @sections = Section.all
    @headings = Heading.all
  end
end

app/helpers/aboutus_help_helper.rb
module AboutusHelpHelper
end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/headings_helper.rb
module HeadingsHelper
end

app/helpers/home_helper.rb
module HomeHelper

end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/show_helper.rb
module ShowHelper
end

app/views/aboutus_help/aboutus.html.erb
<h1>About Us</h1>


<p>azazazazazzaza</p>

app/views/aboutus_help/help.html.erb
<h1>Help</h1>
<p>zazazazazaza</p>

app/views/dashboard/index.html.erb
<h1>Welcome to Dashboard</h1>

<div id="user_nav">
  <%= current_user.email %>


</div>

app/views/headings/_form.html.erb
<%= form_for(@heading) do |f| %>
    <% if @heading.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@heading.errors.count, "error") %> prohibited this heading from being saved:</h2>

          <ul>
            <% @heading.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :H_Name %>
    </div>
    <div class="field">
      <%= f.label :phone %><br>
      <%= f.text_field :H_Phone %>
    </div>
    <div class="field">
      <%= f.label :address %><br>
      <%= f.text_field :H_Address %>
    </div>
    <div class="field">
    <%= select_tag 'heading[section_id]', options_for_select(@sectionn.collect{ |s| [s.Sec_Name, s.id] } ) %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/headings/_search.html.erb
<div style="margin: 50px">
  <%= form_tag headings_index_path, :method => :get do  %>

      <p>
      <div class="field">

        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Search", :H_Name => nil %>


<% end %>
</div>
  </p>
</div>

app/views/headings/index.html.erb
<%= render partial: 'headings/search' %>

<h1>Listing headings</h1>



<table>
  <thead>
  <tr>
    <th>Name </th>
    <th>Phone</th>
    <th>Address</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @headings.each do |heading| %>
      <tr>
        <td><%= heading.H_Name %></td>
        <td><%= heading.H_Phone %></td>
        <td><%= heading.H_Address %></td>




      </tr>
  <% end %>
  </tbody>
</table>

<br>

app/views/headings/new.html.erb
<h1>New heading</h1>
<% if user_signed_in? %>
<%= render 'form' %>

<%= link_to 'Back', headings_path %>
<% else %>
<%= "Sign in or Sign up!!!" %>
<% end %>

app/views/headings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @heading.H_Name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @heading.H_Phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @heading.H_Address %>
</p>

<p>
  <strong>Categorie:</strong>

  <%= @section.Sec_Name %>
</p>

<%= link_to 'Back', homepage_index_path, :method => :get %>

app/views/homepage/index.html.erb
<div class="col-md-2">
  <%= render partial: 'sections/section' %>
</div>
<div class="container col-md-6">
  <div class="starter-template">
    <h1>

      Last three companies

    </h1>
    <p class="lead">

      <% @last_three.each do |head| %>
          <%= head.H_Name %>
          <%= head.H_Address %>
          <%= head.H_Phone %> <br>

    <% end %>
</div>
    </p>
  </div>
</div>
<!--

 /.container

-->
<!--

 Bootstrap core JavaScript
    ===================…

-->
<!--

 Placed at the end of the document so the pages lo…

-->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="../../dist/js/bootstrap.min.js"></script>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" data-target=".navbar-collapse" data-toggle="collapse" type="button">
                            <span class="sr-only">

                                Toggle navigation

                            </span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active">
          <%= link_to 'Home', homepage_index_path %>
        </li>
        <li>
          <%= link_to 'About Us', aboutus_help_aboutus_path %>
        </li>
        <li>
          <%= link_to 'Help', aboutus_help_help_path %>
        </li>
        <li>
          <%= link_to 'Sign in', new_user_session_path, :method => :get %>
                <% if user_signed_in? %>
         <li> <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
            <% else %>
            <li> <%= link_to 'Sign up', new_user_registration_path, :method => :get %></li>
        <% end %>
              </li>
        <li>
          <%= link_to 'Search',headings_index_path , :method => :get %>
        </li>
        <li>
          <%= link_to 'New companie', new_heading_path %>
        </li>
      </ul>

    </div>
    <!--


    /.nav-collapse

    -->
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Devise</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |name,msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>
<%= render partial: 'layouts/header' %>
<div class="main_content">
    <%= yield %>
</div>

</body>
</html>

app/views/sections/_section.html.erb
<h1>Sections</h1>
<% @sections.each do |sections| %>
    <strong><%= sections.Sec_Name %></strong>
    <% @headings.each do |head| %>
        <% if head.section_id == sections.id %>
            <table>
              <tr>
                <td> <%= link_to head.H_Name, head %></td>
              </tr>
            </table>
        <% end %>
    <% end %>
    <br>
<% end %>

app/views/sections/index.html.erb
<%= render partial: 'sections/section' %>